### ISSUE TITLE
Clearer explanations about what each thing does, when to apply it, and whats optional.

### ISSUE THREAD

**Issue by 0x6b-dev** [devangshekhawat/Fedora-36-Post-Install-Guide#2]
Hey, I realise that this might be your own personal repository - but you happen to be the second result found on Google relating to Fedora and battery life issues.

I've got a Dell Inspiron laptop and I had a few questions related to your install guide.

May I suggest you add a few things:

- A clear explanation about what each thing does.
- An explanation about when and why to implement the fixes.
- eg. Why install Nvidia drivers if you have an AMD card. Or performing battery life fixes on a desktop PC with no battery. Or whether System76 fixes are specific to S76 devices. Gnome fixes, if you're not using Gnome...

**Comment by devangshekhawat** [comment]
Thank you for the feedback, I commented on some stuff about what does what, please take a look at it and tell me if I missed out on something.

**Comment by devangshekhawat** [comment]
Hey, it's been a week please let me know if I should make any further changes.

**Comment by 0x6b-dev** [comment]
Apologies for the delay. This is already looking significantly better. Thank you for the update!

**Comment by devangshekhawat** [comment]
Thank you for the kind words!
I did a few more edits. Please let me know what you think.
Can I close this issue now?

**Comment by 0x6b-dev** [comment]
Looks great, its in a much better state now.

Feel free to close.
